development: &default
  secret_key_base: "8fa5ee056fe9918a5aff8e7ec3b301"
  devise_secret_key: "7eae15a2204f7addcb24e0437f2136"
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>

test:
  <<: *default

production: &production
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
  analytics_id: <%= ENV["ANALYTICS_ID"] %>
  analytics_host: <%= ENV["ANALYTICS_HOST"] %>

staging:
  <<: *default
