development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitfab2_development
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

redis:
  host: localhost
  port: 6379
  db: 0
  options:
  namespace: gitfab2_development

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gitfab2_test
  pool: 5
  username: root
  password: root
  socket: /var/lib/mysql/mysql.sock

redis:
  host: localhost
  port: 6379
  db: 0
  options:
  namespace: gitfab2_test

